language: node_js
node_js:
  - '8'
install: yarn install
script:
  - yarn build
  - docker build -t maybush/dockerdemo2 .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push maybush/dockerdemo2
